# Generated by Django 6.1 on 2026-09-10 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_plazo_options_remove_plazo_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(choices=[('card', 'Tarjeta'), ('bizum', 'Bizum'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='card', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('stripe_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(choices=[('duplicate', 'Duplicado'), ('fraudulent', 'Fraude'), ('requested_by_customer', 'Solicitado por el cliente')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gestionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='pagos.pago')),
            ],
        ),
    ]
