# Generated by Django 6.1 on 2026-08-31 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('electrico', 'Eléctrico')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ocupada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plaza',
                'verbose_name_plural': 'Plazas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plaza')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-dia'],
                'unique_together': {('plaza', 'dia')},
            },
        ),
    ]
