# Generated by Django 6.1 on 2026-09-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_desde', models.TimeField()),
                ('horario_hasta', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazos', to='core.plaza')),
            ],
            options={
                'verbose_name': 'Plazo disponible',
                'verbose_name_plural': 'Plazos disponibles',
                'ordering': ['plaza', 'fecha', 'horario_desde'],
            },
        ),
    ]
