# Generated by Django 6.1 on 2026-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plaza',
            options={'ordering': ['nivel', 'numero'], 'verbose_name': 'Plaza', 'verbose_name_plural': 'Plazas'},
        ),
        migrations.AddField(
            model_name='plaza',
            name='nivel',
            field=models.CharField(default='Sotano 1', max_length=10),
        ),
    ]
