# Generated by Django 6.1 on 2026-09-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_reserva_cliente'),
        ('core', '0004_alter_plaza_options_plaza_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plaza',
            options={'ordering': ['nivel', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plaza',
            unique_together={('nivel', 'numero')},
        ),
        migrations.AddField(
            model_name='plaza',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plaza',
            name='pixel_x',
            field=models.IntegerField(default=100, help_text='Posición X en píxeles de la imagen'),
        ),
        migrations.AddField(
            model_name='plaza',
            name='pixel_y',
            field=models.IntegerField(default=100, help_text='Posición Y en píxeles de la imagen'),
        ),
        migrations.AddField(
            model_name='plaza',
            name='radio',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.plazo'),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='nivel',
            field=models.CharField(choices=[('Sótano 1', 'Sótano 1'), ('Sótano 2', 'Sótano 2'), ('Planta 0', 'Planta 0'), ('Planta 1', 'Planta 1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clientes.cliente'),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='plaza',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='ocupada',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='tipo',
        ),
    ]
