# Generated by Django 6.1 on 2026-09-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_reserva_cliente'),
        ('core', '0005_alter_plaza_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo'),
        ),
    ]
