# Generated by Django 6.1 on 2026-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
