# Generated by Django 6.1 on 2026-09-03 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reserva_expira_en'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plaza',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='nivel',
            field=models.CharField(choices=[('Planta 0', 'Planta 0'), ('Sótano 1', 'Sótano 1'), ('Sótano 2', 'Sótano 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='numero',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='pixel_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='pixel_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='radio',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddConstraint(
            model_name='plaza',
            constraint=models.UniqueConstraint(fields=('nivel', 'numero'), name='plaza_unica_por_nivel_numero'),
        ),
    ]
