# Generated by Django 6.1 on 2026-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin de reserva'),
        ),
    ]
