# Generated by Django 6.1 on 2026-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reserva_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='expira_en',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.plazo', verbose_name='Fecha de inicio de reserva (Plazo)'),
        ),
    ]
