# Generated by Django 6.1 on 2026-09-09 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_reserva_expira_en_alter_reserva_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.plazo', verbose_name='Fecha de inicio de reserva'),
        ),
    ]
