# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reserva_plazo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plazo',
            options={'ordering': ['plaza', 'fecha_inicio'], 'verbose_name': 'Plazo disponible', 'verbose_name_plural': 'Plazos disponibles'},
        ),
        migrations.RemoveField(
            model_name='plazo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='plazo',
            name='horario_desde',
        ),
        migrations.RemoveField(
            model_name='plazo',
            name='horario_hasta',
        ),
        migrations.AddField(
            model_name='plazo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='plazo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='plazo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
