# Generated by Django 6.1 on 2026-09-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nivel', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nivel', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_desde', models.TimeField()),
                ('horario_hasta', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazos', to='clientes.plaza')),
            ],
            options={
                'verbose_name': 'Plazo disponible',
                'verbose_name_plural': 'Plazos disponibles',
                'ordering': ['plaza', 'fecha', 'horario_desde'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.plaza')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
