# Generated by Django 6.1 on 2026-09-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_vehiculo_color_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_reservas', to='clientes.cliente'),
        ),
    ]
