# Generated by Django 6.1 on 2026-09-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_reserva_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='plaza',
        ),
        migrations.RemoveField(
            model_name='plazo',
            name='plaza',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Plaza',
        ),
        migrations.DeleteModel(
            name='Plazo',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
